pipeline {
    
	agent any
	
	environment {
        cluster = "vproappprod"
        service = "vproappprodsvc"
    }

    stages {
        stage ('Deploy to Prod ECS') {
            steps {
                withAWS(credentials: 'awscreds', region: 'us-east-1') {
                    sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment'
                }
            }
        }
    }